# Generated by Django 5.0.1 on 2024-02-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothtype', models.CharField(db_column='ClothType', max_length=1)),
                ('noofclothes', models.IntegerField(db_column='NoOfClothes')),
            ],
            options={
                'db_table': 'cloth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.CharField(db_column='CustomerId', max_length=5, primary_key=True, serialize=False)),
                ('customername', models.CharField(db_column='CustomerName', max_length=50)),
                ('customeraddress', models.CharField(db_column='CustomerAddress', max_length=50)),
                ('customernumber', models.IntegerField(db_column='CustomerNumber')),
                ('sex', models.CharField(db_column='Sex', max_length=1)),
                ('customerdate', models.DateField(db_column='CustomerDate')),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('deliveryid', models.CharField(db_column='DeliveryId', max_length=5, primary_key=True, serialize=False)),
                ('deliverydate', models.DateField(db_column='DeliveryDate')),
            ],
            options={
                'db_table': 'delivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.CharField(db_column='OrderId', max_length=5, primary_key=True, serialize=False)),
                ('orderdate', models.DateField(db_column='OrderDate')),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricetype', models.CharField(db_column='PriceType', max_length=1)),
                ('currency', models.DecimalField(db_column='Currency', decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'price',
                'managed': False,
            },
        ),
    ]
